## create credit for users
POST http://localhost:3030/admin/wallets/1/add-credits
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInN1YiI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY4MzEyMDc1LCJleHAiOjE3NjgzMTI5NzV9.-YLRA1pD5bw0a_8GFdDuyypQKabAYhLGAccCwLoTj-8

{
  "amount": 1000
}

//--------------------------------------------------------------------------//
### find all orders (admin)
GET http://localhost:3030/admin/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInN1YiI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY4MzI0Nzc0LCJleHAiOjE3NjgzMjU2NzR9.ZLchGM1SHmwDgf7c3gwJH2Yhhlyrzw0iWhhmLQQCV_U


### approve order (admin)
POST http://localhost:3030/admin/orders/1/approve
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInN1YiI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY4MzI2MjIyLCJleHAiOjE3NjgzMjcxMjJ9.cJEJ4xeMHmKCTQ9cYUoNFaE8Tyd9XCZ6eMKsYJWBcAc

### reject order (admin)
POST http://localhost:3030/admin/orders/2/reject
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInN1YiI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY4MzI2ODE1LCJleHAiOjE3NjgzMjc3MTV9.L6TxJA-r_0O8sz-kihXwMI03RIrRx1Awryf7wCWP4aw