### add order for  user
POST http://localhost:3030/orders
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRleWFhd29yazU0QGdtYWlsLmNvbSIsInN1YiI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3NjgzNzg0ODYsImV4cCI6MTc2ODM3OTM4Nn0.V5xZqdgqZCh252FrquzCHydsPSLpWT-GZW7moxSA9tQ

{
  "productId": 4
}

//--------------------------------------------test for admin ---------------------------------//
### find all orders (admin)
GET http://localhost:3030/orders?page=1&limit=40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInN1YiI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY4Mzc4NTI3LCJleHAiOjE3NjgzNzk0Mjd9._WCyoKa8RODp4QYGJ27T7Aj9_1wSz21-fp7Xz9rwbOs


### approve order (admin)
POST http://localhost:3030/orders/3/approve
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInN1YiI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY4Mzc3MDA2LCJleHAiOjE3NjgzNzc5MDZ9.qnLQLzBdmLRoOBsCe29luIzIuPW7Kutw57vRyF8b-xk

### reject order (admin)
POST http://localhost:3030/orders/2/reject
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInN1YiI6Miwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY4Mzc3MDA2LCJleHAiOjE3NjgzNzc5MDZ9.qnLQLzBdmLRoOBsCe29luIzIuPW7Kutw57vRyF8b-xk
