export enum AutoFailureReason {
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
  ORDER_NOT_PENDING = 'ORDER_NOT_PENDING',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
